#
# QuantumArb 2.0 - Helm Deployment Template for Graph Engine
#
# File: infra/k8s/charts/graph-engine/templates/deployment.yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graph-engine.fullname" . }}
  labels:
    {{- include "graph-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "graph-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graph-engine.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "graph-engine.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
