#
# QuantumArb 2.0 - Helm Deployment Template for VaR Calculator
#
# File: infra/k8s/charts/var-calculator/templates/deployment.yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "var-calculator.fullname" . }}
  labels:
    {{- include "var-calculator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "var-calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "var-calculator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "var-calculator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
