#
# QuantumArb 2.0 - Helm Chart for Risk Gateway
#
# File: infra/k8s/charts/risk-gateway/Chart.yaml
#
# Description:
# This file defines the metadata for the risk-gateway Helm chart.
#
apiVersion: v2
name: risk-gateway
description: A Helm chart for deploying the QuantumArb 2.0 Risk Gateway microservice.
type: application

version: 0.1.0
appVersion: "1.0.0"
