#
# QuantumArb 2.0 - Helm Chart Values for Risk Gateway
#
# File: infra/k8s/charts/risk-gateway/values.yaml
#
# Description:
# Default configuration values for the risk-gateway chart.
#

replicaCount: 2 # Risk gateways are critical, so we run more than one for high availability.

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/risk-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

# Risk services are latency-sensitive and require dedicated resources.
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "1"
    memory: "512Mi"

# Standard Helm chart boilerplate
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
